version: '3.8'

services:
    mongodb:
        image: mongo:latest
        container_name: mongodb_container
        restart: unless-stopped
        ports:
            - '27017:27017'
        volumes:
            - mongo-data:/data/db
        environment:
            MONGO_INITDB_ROOT_USERNAME: root
            MONGO_INITDB_ROOT_PASSWORD: password
        healthcheck:
            test: echo 'db.runCommand(\"ping\").ok' | mongosh localhost:27017/test --quiet
            interval: 10s
            timeout: 10s
            retries: 5
            start_period: 40s
        networks:
            - microservices-network

    rabbitmq:
        image: rabbitmq:management
        container_name: rabbitmq_container
        restart: unless-stopped
        ports:
            - '5672:5672'
            - '15672:15672'
        environment:
            RABBITMQ_DEFAULT_USER: guest
            RABBITMQ_DEFAULT_PASS: guest
        healthcheck:
            test: rabbitmq-diagnostics -q ping
            interval: 30s
            timeout: 30s
            retries: 3
        networks:
            - microservices-network

    user:
        build:
            context: ./user-service
            dockerfile: Dockerfile
        container_name: user_service_container
        restart: always
        depends_on:
            - mongodb
            - rabbitmq
        ports:
            - "8081:8081" # Development uchun portni ochish
        environment:
            NODE_ENV: production
            MONGO_URI: mongodb://root:password@mongodb:27017/user-service-db?authSource=admin
            MESSAGE_BROKER_URL: amqp://guest:guest@rabbitmq:5672
            JWT_SECRET: mening_juda_maxfiy_kalitim_12345
        healthcheck:
            test: ["CMD", "curl", "-f", "http://localhost:8081/health"] # /health endpointini qo'shish kerak
            interval: 30s
            timeout: 10s
            retries: 3
            start_period: 30s
        networks:
            - microservices-network

    chat:
        build:
            context: ./chat-service
            dockerfile: Dockerfile
        container_name: chat_service_container
        restart: always
        depends_on:
            - mongodb
            - rabbitmq
            - user
        ports:
            - "8082:8082" # Development uchun portni ochish
        environment:
            NODE_ENV: production
            MONGO_URI: mongodb://root:password@mongodb:27017/chat-service-db?authSource=admin
            MESSAGE_BROKER_URL: amqp://guest:guest@rabbitmq:5672
            JWT_SECRET: mening_juda_maxfiy_kalitim_12345
        healthcheck:
            test: ["CMD", "curl", "-f", "http://localhost:8082/health"] # /health endpointini qo'shish kerak
            interval: 30s
            timeout: 10s
            retries: 3
            start_period: 30s
        networks:
            - microservices-network

    notification:
        build:
            context: ./notification-service
            dockerfile: Dockerfile
        container_name: notification_service_container
        restart: always
        depends_on:
            - rabbitmq
        ports:
            - "8083:8083" # Development uchun portni ochish
        environment:
            NODE_ENV: production
            MESSAGE_BROKER_URL: amqp://guest:guest@rabbitmq:5672
            SMTP_HOST: smtp-relay.brevo.com
            SMTP_PORT: 587
            SMTP_USER: mening_brevo_account_emailim@example.com
            SMTP_PASS: mening_brevo_master_passwordim
            EMAIL_FROM: chat-server@meningdomenim.com
            SENDINBLUE_APIKEY: mening_brevo_api_kalitim
        healthcheck:
            test: ["CMD", "curl", "-f", "http://localhost:8083/health"] # /health endpointini qo'shish kerak
            interval: 30s
            timeout: 10s
            retries: 3
            start_period: 30s
        networks:
            - microservices-network

    gateway:
        build:
            context: ./gateway
            dockerfile: Dockerfile
        container_name: api_gateway_container
        ports:
            - '8080:8080'
        restart: always
        depends_on:
            - user
            - chat
            - notification
        environment:
            PORT: 8080
        networks:
            - microservices-network

    nginx:
        image: nginx:alpine
        container_name: nginx_proxy_container
        ports:
            - "80:80"
            - "443:443" # Agar SSL/TLS ishlatilsa
        volumes:
            - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
            # SSL sertifikatlari uchun (agar mavjud bo'lsa)
            # - ./nginx/certs:/etc/nginx/certs:ro
        depends_on:
            - gateway
        restart: always
        networks:
            - microservices-network

volumes:
    mongo-data:

networks:
    microservices-network:
        driver: bridge
